import { Spinner } from '../../components/ui/Spinner'
import { AddUserFormModal, DeleteUserConfirmModal, EditUserFormModal, UserStatCard, UsersPagination, UsersTable, UsersToolbar } from '../../components/Users-Ui'
import { useUsersState } from '../../hooks/useUsersState'

const stats = [{ id: 'active-users', label: 'Active Users', icon: 'user', accent: 'blue' }, { id: 'pending-users', label: 'Pending Users', icon: 'user', accent: 'cyan' }, { id: 'banned-users', label: 'Banned Users', icon: 'user-x', accent: 'orange' }]

export function Users({ onViewUserProfile, profile }) {
  const s = useUsersState({ profile, onViewUserProfile })
  return <main className="mx-auto max-w-350 flex-1 bg-[#eef2f8] px-4 py-6 md:px-6 lg:px-8"><div className="flex flex-col gap-5"><header className="flex items-center gap-3"><h1 className="text-2xl font-semibold text-slate-900">Users</h1><span className="grid h-6 w-6 place-items-center rounded-full border border-slate-300 text-xs text-slate-600">!</span></header><div className="grid gap-4 md:grid-cols-2">{stats.map((item) => <UserStatCard key={item.id} {...item} value={String(item.id === 'active-users' ? s.stats.active : item.id === 'pending-users' ? s.stats.pending : s.stats.banned)} />)}</div><section className="rounded-2xl bg-white shadow-sm border border-slate-200"><UsersToolbar searchPlaceholder="Search" primaryAction="Add User" searchTerm={s.searchTerm} sortBy={s.sortBy} filterBy={s.filterBy} sortOptions={['Newest', 'Oldest', 'Name']} filterOptions={['All', 'Active', 'Pending', 'Banned']} onSearchChange={s.handleSearchChange} onSortChange={s.handleSortChange} onFilterChange={s.handleFilterChange} onAddUserClick={() => s.setIsAddUserModalOpen(true)} disableAddUser={!s.canCreateUsers} />{s.selectedVisibleUserIds.length > 0 && s.canToggleBan && <div className="flex flex-wrap items-center gap-2 px-4 mt-3 pb-3"><span className="text-sm text-slate-600">{s.selectedVisibleUserIds.length} selected</span><button type="button" onClick={s.handleBulkUnbanUsers} disabled={s.isBulkUnbanning || s.isBulkBanning}>{s.isBulkUnbanning && <Spinner size="sm" />}Activate Selected</button><button type="button" onClick={s.handleBulkBanUsers} disabled={s.isBulkBanning || s.isBulkUnbanning}>{s.isBulkBanning && <Spinner size="sm" />}Ban Selected</button></div>}<UsersTable users={s.visibleUsers} selectedUserIds={s.selectedVisibleUserIds} onToggleSelectUser={s.handleToggleSelectUser} onToggleSelectAllUsers={s.handleToggleSelectAllVisibleUsers} onViewUser={s.handleViewUser} onEditUser={s.handleEditUser} onToggleBanUser={s.handleToggleBanUser} onDeleteUser={s.setUserPendingDeletion} canToggleBan={s.canToggleBan} isLoading={s.isLoading} processingUserIds={s.processingUserIds} /><UsersPagination currentPage={s.activePage} totalPages={s.totalPages} visiblePages={s.visiblePages} onPageChange={s.handlePageChange} onNextPage={s.handleNextPage} onPreviousPage={s.handlePreviousPage} /></section><AddUserFormModal isOpen={s.isAddUserModalOpen} onClose={() => s.setIsAddUserModalOpen(false)} onSubmit={s.handleAddUserSubmit} /><EditUserFormModal key={s.selectedUser?.id ?? 'edit-user-modal'} user={s.selectedUser} isOpen={s.isEditUserOpen} onClose={s.closeEditModal} onSubmit={s.handleEditUserSubmit} /><DeleteUserConfirmModal user={s.userPendingDeletion} isOpen={Boolean(s.userPendingDeletion)} isDeleting={s.userPendingDeletion ? s.processingUserIds.has(s.userPendingDeletion.id) : false} onCancel={() => s.setUserPendingDeletion(null)} onConfirm={s.handleDeleteUser} /></div></main>
}
